[package]
name = "snake_pixels"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8"
log = "0.4"
pixels = "0.5"
wgpu = "0.9.0"
winit = "0.25"
